name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # アプリケーションディレクトリに移動
          cd ~/converter-web
          
          # 最新のコードを取得
          git pull origin main
          
          # Dockerコンテナを停止（存在する場合）
          docker-compose down || true
          
          # Dockerイメージをビルドして起動
          docker-compose up -d --build
          
          # 古い未使用のイメージを削除
          docker image prune -f
          
          # ログを確認（最後の20行）
          docker-compose logs --tail=20